#!/usr/bin/perl

use strict;
use FindBin;
use Data::Dumper;
use Carp;
use LINZ::BERN::Environment;
use File::Which;
use LINZ::GNSS::Time qw/seconds_datetime seconds_yearday/;

my $env = new LINZ::BERN::Environment;

# Script to run the gnss2brncrd program installed with the LINZ::BERN perl package

if(0)
{
    print "Environment:\n";
    print Dumper(\%ENV);
}
if(0)
{
    print "\n\nMenu parameters\n";
    print Dumper($env->params);
}

my $crdin=$env->param('CRDIN',1);
my $crdout=$env->param('CRDOUT',1);
my $flgupd=$env->param('FLGUPDT');
my $maxdiff=$env->param('MAXDIFF')+0 || 30;
my $strategy=$env->param('STRATEGY');
my $ndays=$env->param('NDAYS')+0 || 30;
my $mindays=$env->param('MINDAYS')+0 || $ndays/2;
my $method=$env->param('METHOD');
$method = 'MEAN' if !$method ne 'MEDIAN';
my $updcodes=$env->param('CODES');


my $date=seconds_datetime(time(),1);
my $sessinfo=$env->param('SES_INFO');
my $year=$env->param('YR4_INFO');
my $user=$env->param('USER');
my $title=$env->param('TITLE');

my $gnss2bernprog='gnss2berncrd';

$crdout=$crdin if $crdout eq '';

print " ===============================================================================\n";
print " LINZ Bernese Version 5.2 Utilities\n";
print " -------------------------------------------------------------------------------\n";
print " Program        : NZGDBCRD\n";
print " Purpose        : Update coordinates from the LINZ geodetic database\n";
print " Default session: $sessinfo year $year\n";
print " Date           : $date\n";
print " User name      : $user\n";
print " ===============================================================================\n";
print " \n";
print " $title\n\n";
print " Input coordinate file:           $crdin\n";
print " Output coordinate file:          $crdout\n";
print " Flag for updated coordinates:    $flgupd\n";
print " Processing strategy for coordinate update:  $strategy\n";
print " Maximum difference for updated coordinates: $maxdiff\n";
print " Number of days to search for coordinates: $ndays\n";
print " Minimum number of sessions for coordinates: $mindays\n";
print " Method for coordinate calculation: $method\n";
print " \n";

my $gnss2crd=which($gnss2bernprog);
if( ! $gnss2crd )
{
    # $env->fail("Cannot find gdb2berncrd program");
}

if( $crdin ne '' && ! -f $crdin )
{
    $env->fail("Cannot find input .CRD file $crdin");
}

$crdout = $crdin if $crdout eq '';

if( $crdout eq '' )
{
    $env->fail("Output coordinate file not defined");
}

# Convert strategy to + separated list
$strategy =~ s/\+/ /g;
$strategy =~ s/^\s+|\s+$//g;
$strategy =~ s/\s+/+/g;


if( $strategy eq '' )
{
    $env->fail("Processing strategy for coordinate update not defined");
}

my @codes=();
foreach my $code (split(' ',$updcodes))
{
    if( $code =~ /^\w{4}$/ )
    {
        push(@codes,uc($code));
    }
    else
    {
        $env->warn("$code is not a valid code - ignored");
    }
}

my ($start,$end)=$env->session_startend();
my ($syear,$sday)=seconds_yearday(($start+$end)/2.0);
my $yearday=sprintf("%04d:%03d",$syear,$sday);

my @command=($gnss2crd,'-V');
push(@command,'-i',$crdin) if $crdin && $crdin ne $crdout;
push(@command,'-o') if $crdin ne $crdout;
push(@command,'-f',$flgupd) if $flgupd ne '';
push(@command,'-m',$maxdiff) if $maxdiff > 0.0;
push(@command,'-P',$ndays);
push(@command,'-R',$mindays) if $mindays > 0;
push(@command,'-M') if $method eq 'MEDIAN';
push(@command,$crdout);
push(@command,$yearday);
push(@command,$strategy);
push(@command,@codes);

print " Running command ",join(' ',@command),"\n";
system(@command); 
if( $? == -1 )
{
    $env->fail("Failed to run $gnss2bernprog: $!");
}
if( $? & 127 )
{
    $env->warn("Error encountered running $gnss2bernprog");
}
if( ! -f $crdout || -M $crdout > 0 )
{
    $env->fail("Failed to update output .CRD file $crdout");
}
print " Coordinate file updated\n";

